# -*- coding: utf-8 -*-
"""
moldes.py — VERSÃO 2 (turbinada com linguagem informal)

O que mudou da v1 para a v2:
  - MUITO mais moldes informais ("tá vendendo", "o povo paga", "encalhado")
  - Reforço pesado nas 4 intenções que zeraram no teste real:
    desempenho_vendedor, produtos_sem_saida, vendas_por_canal, vendas_por_pagamento
  - Mais valores nas entidades fracas (cliente, vendedor, canal, pagamento)

Continua sendo o único arquivo que a equipe edita no dia a dia.

REGRAS
------
1. Use SOMENTE os slots que existem em VALORES.
2. Para repetir o mesmo tipo na frase: {periodo} e {periodo2}.
3. Frase com e sem período = DOIS moldes.
4. Escreva como o gestor FALA: gíria, abreviação, sem acento, sem "?".
"""

VALORES = {
    "periodo": [
        "março", "abril", "janeiro", "fevereiro", "maio", "junho", "julho",
        "agosto", "setembro", "outubro", "novembro", "dezembro",
        "marco",
        "este mês", "esse mês", "mês passado", "o mês passado", "mes passado",
        "esta semana", "essa semana", "semana passada", "a semana passada",
        "hoje", "ontem", "anteontem",
        "2024", "2025", "2026",
        "o último trimestre", "o primeiro trimestre", "o segundo trimestre",
        "o primeiro semestre", "o segundo semestre",
        "os últimos 30 dias", "os últimos 7 dias", "os últimos 3 meses",
        "o ano passado", "este ano", "esse ano", "esse ano todo",
        "março de 2024", "abril de 2025", "dezembro do ano passado",
    ],
    "data": [
        "01/03/2024", "15/04/2025", "10/05/2025", "23/12/2024",
        "02/01/2026", "28/02/2025", "31/07/2024", "12/11/2025",
        "05/05/2025", "18/08/2024", "09/09/2024",
        "15 de março", "3 de abril", "20 de maio", "7 de setembro",
        "3 de abril de 2024", "10 de janeiro de 2025", "25 de dezembro de 2025",
    ],
    "produto": [
        "camiseta branca", "notebook", "caneca azul", "tênis de corrida",
        "fone de ouvido", "mochila", "teclado mecânico", "cadeira gamer",
        "camisa polo", "calça jeans", "mouse sem fio", "garrafa térmica",
        "vestido floral", "carregador", "monitor", "camiseta", "boné",
        "relógio", "chinelo", "óculos de sol",
    ],
    "categoria": [
        "eletrônicos", "vestuário", "calçados", "acessórios", "informática",
        "papelaria", "bebidas", "casa e decoração", "roupas", "perfumaria",
        "eletronicos", "esportes", "brinquedos", "beleza",
    ],
    "cliente": [
        "joão silva", "maria souza", "ana costa", "pedro lima",
        "carla mendes", "ricardo alves", "beatriz", "fernando",
        "lucas oliveira", "patrícia ramos", "joão", "maria", "ana",
        "seu josé", "dona cida", "rafael", "juliana martins",
    ],
    "vendedor": [
        "carlos", "fernanda", "roberto", "juliana", "marcos",
        "amanda", "bruno", "camila santos", "diego", "eduarda lima",
        "paulo", "sandra", "o carlos", "a fernanda", "a juliana",
        "rodrigo", "vanessa", "thiago", "o roberto", "a amanda",
        "o bruno", "a sandra", "o paulo", "gabriel", "leticia",
        "o diego", "a camila", "marcelo", "o marcos", "renata",
    ],
    "canal": [
        "site", "loja física", "loja", "whatsapp", "marketplace",
        "instagram", "telefone", "e-commerce", "balcão", "app",
        "zap", "insta", "loja online", "presencial", "internet",
        "mercado livre", "shopee",
    ],
    "pagamento": [
        "cartão", "cartão de crédito", "cartão de débito", "pix",
        "boleto", "dinheiro", "crédito", "débito", "vale alimentação",
        "cartao", "à vista", "parcelado", "cartão de loja",
    ],
    "numero": [
        "3", "5", "10", "15", "20", "7", "8", "12", "25", "50", "100",
        "três", "cinco", "dez", "vinte", "quinze",
        "vinte e cinco", "vinte e um", "trinta e cinco",
    ],
}

MOLDES = {
    "total_vendas_periodo": [
        "quanto faturei em {periodo}",
        "quanto faturei {periodo}",
        "qual foi o faturamento de {periodo}",
        "qual o faturamento de {periodo}?",
        "total de vendas em {periodo}",
        "total de vendas {periodo}",
        "quanto vendi em {periodo}",
        "quanto vendi {periodo}",
        "me mostra o faturamento de {periodo}",
        "quanto a loja faturou em {periodo}",
        "qual o total vendido em {periodo}",
        "faturamento {periodo}",
        "faturamento de {periodo}",
        "quanto de receita eu tive em {periodo}",
        "qnt vendi em {periodo}",
        "quanto q eu faturei em {periodo}?",
        "soma das vendas de {periodo}",
        "quanto entrou em {periodo}",
        "quanto entrou de dinheiro em {periodo}",
        "vendas totais {periodo}",
        "quanto o negócio faturou {periodo}",
        "quanto a gente vendeu em {periodo}",
        "quanto rendeu {periodo}",
        "quanto rolou de venda em {periodo}",
        "deu quanto de venda em {periodo}",
        "como foi o faturamento de {periodo}",
        "me diz o total de {periodo}",
        "quanto vendi de {produto}",
        "quanto vendi de {produto} em {periodo}",
        "qual o faturamento de {produto} em {periodo}",
        "quanto faturei com {produto} em {periodo}",
        "total vendido de {produto} em {periodo}",
        "quanto saiu de {produto} {periodo}",
        "quanto faturei no dia {data}",
        "qual o faturamento do dia {data}",
        "quanto vendi em {data}",
        "quanto vendi no dia {data}",
        "total de vendas do dia {data}",
        "quanto entrou no dia {data}",
        "vendas do dia {data}",
    ],
    "top_produtos": [
        "quais os {numero} produtos mais vendidos",
        "quais foram os {numero} produtos mais vendidos em {periodo}",
        "me mostra o top {numero} de produtos",
        "top {numero} produtos",
        "top {numero} produtos de {periodo}",
        "quais produtos venderam mais em {periodo}",
        "produto mais vendido de {periodo}",
        "qual o produto mais vendido",
        "qual foi meu produto campeão de vendas em {periodo}",
        "ranking de produtos",
        "ranking dos {numero} melhores produtos",
        "o que mais vendeu em {periodo}",
        "o que mais saiu {periodo}",
        "o que mais saiu em {periodo}",
        "quais são os produtos que mais vendem",
        "me lista os {numero} itens mais vendidos de {periodo}",
        "produtos mais vendidos",
        "produtos mais vendidos em {periodo}",
        "qual foi o item com mais saída em {periodo}",
        "quero ver os {numero} produtos com mais saída",
        "quais os produtos que mais venderam {periodo}",
        "qual produto tá saindo mais",
        "qual produto tá vendendo mais em {periodo}",
        "o que vende mais aqui",
        "quais os campeões de venda de {periodo}",
        "meus produtos que mais vendem",
        "qual o carro chefe de {periodo}",
        "o que bombou em {periodo}",
    ],
    "ticket_medio": [
        "qual é o meu ticket médio",
        "qual o ticket médio de {periodo}",
        "qual o ticket medio em {periodo}",
        "ticket médio",
        "ticket médio {periodo}",
        "ticket médio de {periodo}",
        "valor médio em {periodo}",
        "qual o valor médio das minhas vendas",
        "quanto cada cliente gasta em média",
        "quanto cada cliente gastou em média em {periodo}",
        "qual o valor médio por venda em {periodo}",
        "média de valor por compra em {periodo}",
        "me mostra o ticket médio de {periodo}",
        "qual foi o ticket médio em {periodo}?",
        "quanto foi a média por venda {periodo}",
        "gasto médio por cliente em {periodo}",
        "qual meu tkt médio",
        "valor médio por pedido em {periodo}",
        "média por venda de {periodo}",
        "quanto o cliente gasta por compra em média",
        "em média quanto entra por venda em {periodo}",
        "qual a média de cada compra",
        "cada venda dá em média quanto em {periodo}",
        "quanto sai em média por cliente",
        "qual a média de cada compra em {periodo}",
        "quanto sai por venda em média",
        "qual o gasto médio por pedido",
        "média de faturamento por venda em {periodo}",
        "quanto vale cada venda na média de {periodo}",
        "qual o valor médio de compra",
        "em média o quanto cada pedido soma",
        "qual a média de valor das vendas de {periodo}",
        "quanto fica a média por compra",
        "média de quanto sai em cada venda",
    ],
    "comparacao_periodos": [
        "vendi mais em {periodo} ou {periodo2}",
        "vendi mais em {periodo} ou em {periodo2}?",
        "compare {periodo} com {periodo2}",
        "comparação entre {periodo} e {periodo2}",
        "qual foi melhor, {periodo} ou {periodo2}",
        "{periodo} vendeu mais que {periodo2}?",
        "faturei mais em {periodo} ou em {periodo2}",
        "me compara o faturamento de {periodo} e {periodo2}",
        "diferença de vendas entre {periodo} e {periodo2}",
        "compara as vendas de {periodo} contra {periodo2}",
        "em qual mês vendi mais, {periodo} ou {periodo2}",
        "quero comparar {periodo} com {periodo2}",
        "{periodo} x {periodo2}",
        "vendas de {periodo} comparadas com {periodo2}",
        "qual período foi melhor, {periodo} ou {periodo2}",
        "comparativo de {periodo} e {periodo2}",
        "confronto entre {periodo} e {periodo2}",
        "foi melhor {periodo} ou {periodo2}",
        "onde vendi mais, {periodo} ou {periodo2}",
        "qual vendeu mais, {periodo} ou {periodo2}",
        "{periodo} foi melhor que {periodo2}?",
        "me diz se {periodo} bateu {periodo2}",
    ],
    "vendas_por_categoria": [
        "quanto vendi em cada categoria",
        "quanto vendi em cada categoria em {periodo}",
        "vendas por categoria",
        "vendas por categoria em {periodo}",
        "quanto faturei na categoria {categoria}",
        "quanto vendi de {categoria}",
        "quanto vendi de {categoria} em {periodo}",
        "faturamento por categoria de {periodo}",
        "qual categoria vende mais",
        "qual categoria vendeu mais em {periodo}",
        "me mostra o total por categoria",
        "quanto cada categoria faturou em {periodo}",
        "vendas de {categoria}",
        "vendas de {categoria} em {periodo}",
        "desempenho da categoria {categoria} em {periodo}",
        "como estão as vendas de {categoria}",
        "como tá a saída de {categoria}",
        "como tá indo {categoria} em {periodo}",
        "total de {categoria} em {periodo}",
        "faturamento de {categoria} {periodo}",
        "quanto a categoria {categoria} representou em {periodo}",
        "quanto saiu de {categoria} em {periodo}",
        "qual categoria tá bombando",
        "{categoria} tá vendendo bem?",
        "que categoria puxa mais venda em {periodo}",
    ],
    "desempenho_vendedor": [
        "quem é o vendedor com maior faturamento",
        "qual vendedor vendeu mais em {periodo}",
        "quanto o {vendedor} vendeu",
        "quanto {vendedor} vendeu em {periodo}",
        "desempenho dos vendedores",
        "desempenho dos vendedores em {periodo}",
        "ranking de vendedores de {periodo}",
        "ranking de vendedores",
        "vendas por vendedor",
        "vendas por vendedor em {periodo}",
        "qual foi o faturamento de {vendedor} em {periodo}",
        "quem foi meu melhor vendedor",
        "quem foi meu melhor vendedor em {periodo}",
        "quem vendeu mais {periodo}",
        "quem vendeu mais em {periodo}",
        "como foi o desempenho de {vendedor}",
        "como foi o desempenho de {vendedor} em {periodo}",
        "quanto cada vendedor faturou em {periodo}",
        "resultado do {vendedor} em {periodo}",
        "me mostra as vendas da {vendedor}",
        "me mostra as vendas do {vendedor}",
        "o {vendedor} tá vendendo bem?",
        "a {vendedor} tá vendendo bem esse mês?",
        "como o {vendedor} tá indo em {periodo}",
        "quem tá vendendo mais {periodo}",
        "quem tá vendendo mais na loja",
        "quem é meu melhor vendedor esse ano",
        "quem tá puxando as vendas",
        "o {vendedor} vendeu quanto em {periodo}",
        "quanto que o {vendedor} fez em {periodo}",
        "meu melhor vendedor é quem",
        "quem bateu a meta em {periodo}",
        "quem tá indo bem nas vendas",
        "como tão os vendedores em {periodo}",
        "quem vendeu bem em {periodo}",
        "quem é o destaque de vendas de {periodo}",
        "a {vendedor} fez quanto",
        "quanto o {vendedor} trouxe em {periodo}",
        "quanto {vendedor} faturou",
        "quanto o {vendedor} fez",
        "como foi a {vendedor} em {periodo}",
        "o {vendedor} bateu a meta?",
        "me mostra o resultado de {vendedor}",
        "quanto {vendedor} vendeu essa semana",
        "as vendas de {vendedor} tão boas?",
        "o {vendedor} tá indo bem em {periodo}?",
        "quero ver as vendas de {vendedor}",
        "quanto {vendedor} trouxe de faturamento",
        "o {vendedor} vendeu bem em {periodo}?",
        "desempenho de {vendedor} em {periodo}",
    ],
    "top_clientes": [
        "quem são meus {numero} melhores clientes",
        "top {numero} clientes",
        "top {numero} clientes de {periodo}",
        "quais clientes compraram mais",
        "quais clientes compraram mais em {periodo}",
        "quem foi meu melhor cliente",
        "quem foi meu melhor cliente em {periodo}",
        "quem mais comprou em {periodo}",
        "ranking de clientes",
        "ranking dos {numero} maiores clientes de {periodo}",
        "quanto o cliente {cliente} comprou",
        "quanto {cliente} comprou em {periodo}",
        "me mostra os {numero} clientes que mais gastaram",
        "clientes que mais compraram em {periodo}",
        "qual cliente gastou mais {periodo}",
        "lista dos melhores clientes de {periodo}",
        "quem comprou mais de mim em {periodo}",
        "meus maiores clientes",
        "quanto o {cliente} gastou em {periodo}",
        "quanto {cliente} comprou",
        "qual o total de compras de {cliente}",
        "me mostra as compras de {cliente} em {periodo}",
        "o {cliente} comprou quanto em {periodo}",
        "histórico do cliente {cliente}",
        "quanto {cliente} já comprou no total",
        "o {cliente} está comprando bem?",
        "quem mais gastou aqui esse ano",
        "quem mais gasta na loja",
        "quem são meus melhores fregueses",
        "quem compra mais de mim",
        "meus clientes fiéis",
        "quem gastou mais em {periodo}",
    ],
    "vendas_por_canal": [
        "vendi mais pelo {canal} ou pelo {canal2}",
        "vendi mais no {canal} ou no {canal2}?",
        "vendas por canal",
        "vendas por canal em {periodo}",
        "quanto vendi pelo {canal}",
        "quanto vendi pelo {canal} em {periodo}",
        "quanto vendi no {canal} em {periodo}",
        "qual canal vende mais",
        "qual canal vendeu mais em {periodo}",
        "faturamento por canal de {periodo}",
        "quanto o {canal} faturou em {periodo}",
        "desempenho do {canal}",
        "desempenho do {canal} em {periodo}",
        "me mostra as vendas por canal de {periodo}",
        "quanto cada canal vendeu em {periodo}",
        "vendas do {canal} em {periodo}",
        "total vendido pelo {canal}",
        "quanto veio do {canal} em {periodo}",
        "o {canal} tá trazendo venda?",
        "o {canal} tá vendendo bem?",
        "o {canal} tá dando resultado?",
        "vendo mais pelo {canal} ou pelo {canal2}?",
        "de onde vem mais venda, {canal} ou {canal2}",
        "o {canal} tá bombando?",
        "quanto que o {canal} tá trazendo",
        "o pessoal compra mais pelo {canal} ou {canal2}",
        "onde vendo mais, no {canal} ou no {canal2}",
        "quanto rolou de venda no {canal} em {periodo}",
        "o {canal} tá puxando venda em {periodo}?",
        "vende mais no {canal} ou no {canal2}",
        "qual canal tá indo melhor em {periodo}",
        "o {canal} deu quanto em {periodo}",
        "as vendas do {canal} tão boas?",
        "quanto entrou pelo {canal} em {periodo}",
    ],
    "vendas_por_pagamento": [
        "quanto vendi no {pagamento}",
        "quanto vendi no {pagamento} em {periodo}",
        "vendas por forma de pagamento",
        "vendas por forma de pagamento em {periodo}",
        "qual a forma de pagamento mais usada",
        "qual forma de pagamento mais usada em {periodo}",
        "quanto entrou via {pagamento}",
        "quanto recebi em {pagamento} em {periodo}",
        "faturamento por meio de pagamento de {periodo}",
        "total no {pagamento}",
        "total em {pagamento} de {periodo}",
        "me mostra as vendas por pagamento de {periodo}",
        "quanto cada forma de pagamento representou em {periodo}",
        "vendas em {pagamento} de {periodo}",
        "quanto foi pago com {pagamento}",
        "quanto foi pago com {pagamento} em {periodo}",
        "o povo paga mais no {pagamento} ou no {pagamento2}",
        "o pessoal paga mais no {pagamento} ou no {pagamento2}",
        "o {pagamento} tá vendendo mais que o {pagamento2}?",
        "vende mais no {pagamento} ou no {pagamento2}",
        "as pessoas pagam mais no {pagamento} ou {pagamento2}",
        "recebo mais no {pagamento} ou no {pagamento2}",
        "quanto entrou de {pagamento} em {periodo}",
        "quanto que caiu no {pagamento} em {periodo}",
        "o {pagamento} representa quanto das vendas",
        "quanto o povo pagou no {pagamento}",
        "a galera paga mais no {pagamento} ou {pagamento2}",
        "quanto rolou de {pagamento} em {periodo}",
        "que forma de pagamento o povo usa mais",
        "como o pessoal paga mais em {periodo}",
        "quanto vendi parcelado em {periodo}",
        "quanto foi no {pagamento} em {periodo}",
    ],
    "produtos_sem_saida": [
        "quais produtos não venderam {periodo}",
        "quais produtos não venderam em {periodo}",
        "produtos sem saída",
        "produtos sem saída em {periodo}",
        "quais produtos estão parados",
        "o que não vendeu em {periodo}",
        "quais itens não tiveram venda em {periodo}",
        "produtos encalhados",
        "me mostra os produtos parados de {periodo}",
        "quais produtos venderam menos em {periodo}",
        "produtos com baixa saída",
        "produtos com baixa saída em {periodo}",
        "o que está encalhado",
        "quais produtos não saíram {periodo}",
        "itens sem venda em {periodo}",
        "quais produtos tiveram menos saída",
        "quais produtos tiveram menos saída em {periodo}",
        "produtos que não venderam nada em {periodo}",
        "tem alguma coisa encalhada no estoque",
        "tem produto encalhado?",
        "o que tá encalhado na loja",
        "o que tá parado no estoque",
        "tem coisa parada no estoque?",
        "o que não tá saindo",
        "o que não tá vendendo em {periodo}",
        "quais produtos tão parados",
        "que produto não vende de jeito nenhum",
        "o que tá empacado no estoque",
        "tem mercadoria parada?",
        "o {produto} tá parado?",
        "o {produto} vendeu em {periodo}?",
        "quais produtos tão sem giro",
        "o que tá pegando poeira no estoque",
        "tem produto que não sai",
        "o que tá difícil de vender",
        "quais itens tão encalhados em {periodo}",
    ],
    "variacao_periodo": [
        "quanto cresci em relação a {periodo}",
        "qual foi a variação de {periodo} para {periodo2}",
        "cresci ou caí em {periodo}?",
        "qual o crescimento de {periodo}",
        "minhas vendas subiram ou caíram em {periodo}",
        "de quanto foi a queda em {periodo}",
        "variação percentual entre {periodo} e {periodo2}",
        "quantos por cento eu cresci em {periodo}",
        "as vendas de {periodo} cresceram?",
        "evolução das vendas em {periodo}",
        "qual a taxa de crescimento de {periodo} para {periodo2}",
        "quanto aumentei em relação a {periodo}",
        "crescimento em {periodo}",
        "minhas vendas melhoraram em {periodo}?",
        "qual foi meu crescimento percentual em {periodo}",
        "variação de vendas em {periodo}",
        "quanto por cento subiu de {periodo} para {periodo2}",
        "eu cresci ou caí em relação ao mês passado",
        "as vendas melhoraram ou pioraram em {periodo}",
        "tô vendendo mais que em {periodo}?",
        "minha venda subiu em {periodo}?",
        "caiu muito a venda em {periodo}?",
        "quanto que aumentou de {periodo} pra {periodo2}",
        "minhas vendas tão subindo?",
        "melhorei em relação a {periodo}?",
    ],
    "quantidade_vendas": [
        "quantas vendas fiz {periodo}",
        "quantas vendas fiz em {periodo}",
        "quantas vendas eu tive em {periodo}",
        "número de vendas em {periodo}",
        "quantos pedidos em {periodo}",
        "quantos pedidos eu tive {periodo}",
        "quantidade de vendas",
        "quantidade de vendas em {periodo}",
        "quantas transações eu fiz em {periodo}",
        "quantas compras foram feitas em {periodo}",
        "total de pedidos de {periodo}",
        "me diz quantas vendas tive {periodo}",
        "contagem de vendas em {periodo}",
        "quantas notas emiti em {periodo}",
        "qtas vendas em {periodo}",
        "quantas vendas no total em {periodo}",
        "número de pedidos {periodo}",
        "quantas vendas aconteceram em {periodo}",
        "fiz quantas vendas hoje",
        "quantas vendas rolaram em {periodo}",
        "quantas vendas saíram {periodo}",
        "vendi quantas vezes em {periodo}",
        "quantos pedidos entraram em {periodo}",
        "quantas vendas deram em {periodo}",
        "quantas unidades de {produto} vendi em {periodo}",
        "quantos {produto} vendi em {periodo}",
        "quantas vendas fiz no dia {data}",
        "quantas vendas fechei em {periodo}",
        "número de vendas do dia {data}",
    ],
}

INTENCOES = sorted(MOLDES.keys())
TIPOS_ENTIDADE = ["PERIODO", "DATA", "PRODUTO", "CATEGORIA", "CLIENTE",
                  "VENDEDOR", "CANAL", "PAGAMENTO", "NUMERO"]
TAGS = ["O"] + [f"{bi}-{ent}" for ent in TIPOS_ENTIDADE for bi in ("B", "I")]

assert len(INTENCOES) == 12, f"Esperado 12 intenções, achei {len(INTENCOES)}"
assert len(TAGS) == 19, f"Esperado 19 tags, achei {len(TAGS)}"
